server:
  port: 8080
spring:
  application:
    name: poem
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_poem?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  mapper-locations:
    - classpath*:cn/**/mapper/*.xml
  type-aliases-package: cn.michael.poem.pojo